ALTER TABLE DBSWITCH_ASSIGNMENT_CONFIG ADD COLUMN "table_incr_columns" text DEFAULT NULL;
COMMENT ON COLUMN DBSWITCH_ASSIGNMENT_CONFIG."table_incr_columns" IS '增量同步表的增量字段配置';

ALTER TABLE DBSWITCH_ASSIGNMENT_CONFIG ADD COLUMN "pre_sql_scripts" text DEFAULT NULL;
COMMENT ON COLUMN DBSWITCH_ASSIGNMENT_CONFIG."pre_sql_scripts" IS '源端查询的前置执行sql脚本';

ALTER TABLE DBSWITCH_ASSIGNMENT_CONFIG ADD COLUMN "post_sql_scripts" text DEFAULT NULL;
COMMENT ON COLUMN DBSWITCH_ASSIGNMENT_CONFIG."post_sql_scripts" IS '源端查询的后置执行sql脚本';
